### ISSUE TITLE
Demo data won't be populated

### ISSUE THREAD

**Issue by liberaliscomputing** [hms-dbmi/docker-images#34]
I am following up the README.md in the [quick-start](https://github.com/hms-dbmi/docker-images/tree/master/deployments/irct/quick-start) repo to set up an i2b2 demo container.

When trying to initialize the database by placing either of the following lines:

```
$ docker-compose run --rm irct-init -d irct -r i2b2
$ docker-compose run --rm irct-init -d irct -r dataconverters
```

I encounter the following error:

```
check IRCT DB connection
ERROR 2059 (HY000): Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
```

After a long while of digging into the MySQL documentation and Stack Overflow, I figured this issue comes out ever since MySQL 8.0.4 for MySQL changed the default password plugin.
This issue can normally be handled by adding the following line to the `db:` section at `docker-compose.yml`:

```
command: ["--default-authentication-plugin=mysql_native_password"]
```

for this command lets MySQL refer to the legacy password plugin.

However, the error above still pops up even after adding the command and I also figured it seems solved when the following lines are changed from

```
volumes:
  - mysql-data:/var/lib/mysql
```
to

```
volumes:
  - /var/lib/mysql
```

for the volume setup may interrupt the `db` container to be properly run.

Then, when I try to initialize the database, I end up having another issue.
+ `docker-compose run --rm irct-init -d irct -r i2b2` returns the following error: 

```
ERROR 1146 (42S02) at line 1: Table 'irct.Resource' doesn't exist
./scratch/irct/sql/init-db.sh: line 143: [: -gt: unary operator expected
ERROR 1146 (42S02) at line 15 in file: '/scratch/irct/sql/ResourceInterface_i2b2.sql': Table 'irct.Resource' doesn't exist
confirm IRCT DB populated
ERROR 1146 (42S02) at line 1: Table 'irct.Resource' doesn't exist
```  

+ `docker-compose run --rm irct-init -d irct -r dataconverters` returns the following error: 

```
ERROR 1146 (42S02) at line 1: Table 'irct.DataConverterImplementation' doesn't exist
./scratch/irct/sql/init-db.sh: line 109: [: -gt: unary operator expected
ERROR 1146 (42S02) at line 1: Table 'irct.DataConverterImplementation' doesn't exist
confirm Data Converters added
ERROR 1146 (42S02) at line 1: Table 'irct.DataConverterImplementation' doesn't exist
```

+ When `-c true` is specified, the commands above return the following error:

```
ERROR 1146 (42S02) at line 1: Table 'irct.Resource' doesn't exist
```

Finally, when I take a look into the `db` container by placing `mysql -h 0.0.0.0 -P 3306 -u root -p`, the `irct` database is empty.

**Comment by recursethis** [comment]
the PIC-SURE quick-start works best with mysql 5.7.22. The master branch has been updated to specifically use 5.7.22 instead of "latest." We've recently ran into an issue with the most recent version of the mysql:latest docker image causing a similar error as you are seeing.

at the moment, you have to start PIC-SURE `docker-compose up -d irct` against a clean database to correctly populate the database with the required tables before using the irct-init service to add the data. I'd suggest pulling the latest from the master branch and try it again.

Please notify me if this resolves the issue or if it continues to persist.

**Comment by recursethis** [comment]
We recently updated our quick-start to instead use a pre-populated database so you don't have to install the data yourself. The quick start MySQL database comes pre-populated with the needed data converters and the i2b2.org resource.

Please update to the lastest master branch and run the following commands
```bash
$ docker-compose down
$ docker-compose pull
$ docker-compose up -d
```
and you will be all set. The volume associated with the MySQL database has changed. Your data will now be in volume `quickstart_irct-data` instead of `quickstart_mysql-data`
